[package]
name = "hen"
version = "0.1.0"
authors = ["Jan Weidner <jw3126@gmail.com>"]

[dependencies]
regex = "1.0"
sha3 = "0.7.3"
rayon = "1.0"
num_cpus = "1.8.0"
serde_json = "1.0"
serde = "1.0.45"
serde_derive = "1.0.45"
clap = "2.31"
assert_cli = "0.5"

[dev-dependencies]
